"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os

from django.conf import settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n)3+250s9#7ejm%5k7=w19x!00+1pd&bt8v$d=s5+=bymu_7-w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # Proje ana dizininde 'media' klasörü

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # SessionAuthentication'ı tarayıcı tabanlı API ve admin için tutabiliriz
        'rest_framework.authentication.SessionAuthentication',
        # JWT Authentication'ı ekliyoruz
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        # Varsayılan izinleri burada belirleyebilirsiniz, örneğin:
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
        # Veya daha kısıtlı:
        # 'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10, # Her sayfada kaç öğe olacağı (istediğiniz gibi ayarlayın)
    # Diğer DRF ayarları buraya eklenebilir (Pagination, Filtering vb.)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle', # Anonim (giriş yapmamış) kullanıcılar için
        'rest_framework.throttling.UserRateThrottle'  # Giriş yapmış kullanıcılar için
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',  # Anonim kullanıcılar günde 100 istek yapabilir
        'user': '10000/day', # Giriş yapmış kullanıcılar günde 1000 istek yapabilir
        # Daha detaylı limitler de tanımlanabilir (örn: 'login': '10/hour')
        # ve view bazında uygulanabilir.
    }
}



from datetime import timedelta # timedelta'yı import etmeyi unutmayın

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15), # Access token ömrü (örn: 15 dakika)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),    # Refresh token ömrü (örn: 1 gün)
    'ROTATE_REFRESH_TOKENS': False, # True yapılırsa, refresh endpoint'i her kullanıldığında yeni bir refresh token döner
    'BLACKLIST_AFTER_ROTATION': False, # Eğer ROTATE_REFRESH_TOKENS True ise, eski refresh token'ı karalisteye alır. Token karalistesi için ek kurulum gerekir (simplejwt.token_blacklist app).
    'UPDATE_LAST_LOGIN': False, # Token refresh edildiğinde kullanıcının last_login alanını günceller mi?

    'ALGORITHM': 'HS256', # İmzalama algoritması
    'SIGNING_KEY': settings.SECRET_KEY, # İmzalama için kullanılacak anahtar (SECRET_KEY'i kullanır)
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',), # Header'da token tipini belirtir (örn: 'Authorization: Bearer <token>')
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5), # Kayar tokenlar için ömür
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1), # Kayar tokenlar için refresh ömrü
}

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True